# Standards: 1.2
---
- name: Include OS tasks
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - netplan

- name: Install required packages
  with_items: "{{ netplan_packages }}"
  package:
    name: "{{ item }}"
    state: present
  tags:
    - netplan

- name: Write network config
  notify:
    - Apply netplan
  template:
    src: config.j2
    dest: "{{ netplan_config_file }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  tags:
    - netplan

...
